application: minomo-web-service
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /contexts/.*
  script: context_store.app

libraries:
- name: webapp2
  version: latest

builtins:
- appstats: on
